Semicolon

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -9,4 +9,4 @@ jobs:
         steps:
           - uses: actions/checkout@v4
           - name: Run tests
-            run: ./tests.sh || { echo "::error title=Tests failed::tests.sh returned an error." && exit 1 }
+            run: ./tests.sh || { echo "::error title=Tests failed::tests.sh returned an error." && exit 1; }
